"""
Comparative Design: All pairwise comparison
===========================================

This script compares the 7 candidate designs that were significantly better
than the base in the Bonferroni comparison vs. base.

Designs included:
    15 slots | S3 - Bailey-Welch
    15 slots | S3 - Benchmarking
    15 slots | S3 - FCFS
    15 slots | S3 - Blocking
    15 slots | S2 - Bailey-Welch
    15 slots | S2 - Benchmarking
    15 slots | S2 - FCFS

All pairwise Bonferroni setup:
    k = 7 designs
    c = k(k-1)/2 = 21 pairwise comparisons
    alpha_per_CI = alpha / c = 0.05 / 21
    individual CI level = 1 - alpha/c = 99.762%

Method:
    Bonferroni-corrected confidence intervals on paired batch differences.
    For n paired batch means, the degrees of freedom are df = n - 1.
    OV = elAppWT / 168 + urScanWT / 9
"""

from __future__ import annotations

import itertools
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Patch
from scipy import stats


# ── CONFIG ────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "output"
OUTPUT_DIR = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_OUTPUT_DIR
RESULTS_DIR = SCRIPT_DIR / "all_pairwise_output"

WARMUP = 0
BATCH_SIZE = 65
ALPHA = 0.05  # overall significance level, i.e. overall 95% confidence

RULE_NAMES = {
    1: "FCFS",
    2: "Bailey-Welch",
    3: "Blocking",
    4: "Benchmarking",
}

# These are the 7 combinations that were significantly better than the base.
# Tuple order: (urgent_slots, strategy, rule)
CANDIDATE_DESIGNS = [
    (15, 3, 2),  # S3 - Bailey-Welch
    (15, 3, 4),  # S3 - Benchmarking
    (15, 3, 1),  # S3 - FCFS
    (15, 3, 3),  # S3 - Blocking
    (15, 2, 2),  # S2 - Bailey-Welch
    (15, 2, 4),  # S2 - Benchmarking
    (15, 2, 1),  # S2 - FCFS
]

K_DESIGNS = len(CANDIDATE_DESIGNS)
C_COMPARISONS = K_DESIGNS * (K_DESIGNS - 1) // 2

assert K_DESIGNS == 7, f"Expected k=7 designs, got k={K_DESIGNS}"
assert C_COMPARISONS == 21, f"Expected c=21 comparisons, got c={C_COMPARISONS}"

COLORS = {
    "first_better": "#1D9E75",
    "second_better": "#D85A30",
    "not_significant": "#B4B2A9",
}


GENERATED_OUTPUT_FILES = [
    "all_pairwise_comparison_table.csv",
    "all_pairwise_design_summary.csv",
    "all_pairwise_significance_matrix.csv",
    "all_pairwise_forest_plot.png",
    "all_pairwise_mean_ranking.png",
]


def clean_previous_outputs() -> None:
    """Remove previous generated all-pairwise files from RESULTS_DIR.

    This avoids mixing old Welch outputs with the new paired-output files.
    Only the files generated by this script are removed; raw simulation output is never touched.
    """
    for filename in GENERATED_OUTPUT_FILES:
        path = RESULTS_DIR / filename
        if path.exists():
            path.unlink()


# ── HELPERS ───────────────────────────────────────────────────────────────────
def design_label(slots: int, strategy: int, rule: int) -> str:
    return f"{slots} slots | S{strategy} - {RULE_NAMES[rule]}"


def short_label(slots: int, strategy: int, rule: int) -> str:
    return f"S{strategy}-{RULE_NAMES[rule]}"


def csv_path(strategy: int, slots: int, rule: int) -> Path:
    return OUTPUT_DIR / f"output-S{strategy}-{slots}-rule{rule}.csv"


def load_batch_ov(strategy: int, slots: int, rule: int) -> np.ndarray:
    path = csv_path(strategy, slots, rule)
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}\n"
            f"Check whether OUTPUT_DIR is correct. Current OUTPUT_DIR: {OUTPUT_DIR}"
        )

    df = pd.read_csv(path)
    df.columns = df.columns.str.strip()

    required_cols = {"elAppWT", "urScanWT"}
    missing_cols = required_cols - set(df.columns)
    if missing_cols:
        raise ValueError(f"{path.name} is missing required columns: {missing_cols}")

    post = df.iloc[WARMUP:].copy()
    post["OV"] = post["elAppWT"] / 168.0 + post["urScanWT"] / 9.0

    n_batches = len(post) // BATCH_SIZE
    if n_batches < 2:
        raise ValueError(
            f"Not enough post-warm-up observations in {path.name}: "
            f"{len(post)} rows after warm-up -> {n_batches} batches."
        )

    usable = post.iloc[: n_batches * BATCH_SIZE]
    batch_means = usable["OV"].to_numpy().reshape(n_batches, BATCH_SIZE).mean(axis=1)
    return batch_means


def summarise_batch_means(batch_means: np.ndarray) -> dict:
    n = len(batch_means)
    mean = float(batch_means.mean())
    var = float(batch_means.var(ddof=1))
    se = float(np.sqrt(var / n))
    t95 = stats.t.ppf(0.975, df=n - 1)
    hw95 = float(t95 * se)
    return {
        "n_batches": n,
        "mean_OV": mean,
        "var": var,
        "se": se,
        "df": n - 1,
        "hw95": hw95,
        "lower95": mean - hw95,
        "upper95": mean + hw95,
    }


# ── DATA PREPARATION ──────────────────────────────────────────────────────────
def load_designs() -> dict:
    designs = {}

    for idx, (slots, strategy, rule) in enumerate(CANDIDATE_DESIGNS, start=1):
        label = design_label(slots, strategy, rule)
        batches = load_batch_ov(strategy, slots, rule)
        summary = summarise_batch_means(batches)

        designs[label] = {
            "design_id": f"D{idx}",
            "label": label,
            "short_label": short_label(slots, strategy, rule),
            "urgent_slots": slots,
            "strategy": strategy,
            "rule": rule,
            "rule_name": RULE_NAMES[rule],
            "batches": batches,
            **summary,
        }

    return designs


# ── PAIRED ALL PAIRWISE COMPARISON ────────────────────────────────────────────
def paired_pairwise_interval(design_a: dict, design_b: dict) -> dict:
    """
    Computes a Bonferroni-corrected paired CI for:
        delta = mean(A - B)

    The paired comparison uses the difference between the corresponding
    batch means of design A and design B. Therefore, when n paired batch
    differences are used, the degrees of freedom are df = n - 1.

    Since OV is minimized:
        CI entirely below 0  -> A is significantly better than B
        CI entirely above 0  -> B is significantly better than A
        CI contains 0        -> no significant difference
    """
    batches_a = design_a["batches"]
    batches_b = design_b["batches"]

    n_a = len(batches_a)
    n_b = len(batches_b)
    n = min(n_a, n_b)

    if n < 2:
        raise ValueError(
            f"Not enough paired batches for {design_a['label']} vs {design_b['label']}: n={n}."
        )

    # Use only the common number of batches so that the comparison is paired.
    diffs = batches_a[:n] - batches_b[:n]

    delta = float(diffs.mean())
    se_diff = float(diffs.std(ddof=1) / np.sqrt(n))
    df_pair = n - 1

    alpha_per_ci = ALPHA / C_COMPARISONS
    ci_level = 1 - alpha_per_ci
    t_crit = stats.t.ppf(1 - alpha_per_ci / 2, df=df_pair)
    half_width = float(t_crit * se_diff)

    ci_lower = delta - half_width
    ci_upper = delta + half_width

    if ci_upper < 0:
        result = "A significantly better"
        better_design = design_a["label"]
        better_design_id = design_a["design_id"]
        direction = "first_better"
        interpretation = f"{design_a['label']} is significantly better than {design_b['label']}"
    elif ci_lower > 0:
        result = "B significantly better"
        better_design = design_b["label"]
        better_design_id = design_b["design_id"]
        direction = "second_better"
        interpretation = f"{design_b['label']} is significantly better than {design_a['label']}"
    else:
        result = "not significantly different"
        better_design = ""
        better_design_id = ""
        direction = "not_significant"
        interpretation = "not significantly different"

    return {
        "design_A_id": design_a["design_id"],
        "design_A": design_a["label"],
        "design_B_id": design_b["design_id"],
        "design_B": design_b["label"],
        "mean_A": design_a["mean_OV"],
        "mean_B": design_b["mean_OV"],
        "delta_A_minus_B": delta,
        "se_delta": se_diff,
        "df": df_pair,
        "t_crit": t_crit,
        "half_width_bonferroni": half_width,
        "ci_lower": ci_lower,
        "ci_upper": ci_upper,
        "alpha_overall": ALPHA,
        "alpha_per_ci": alpha_per_ci,
        "ci_level_pct": ci_level * 100,
        "n_batches": n,
        "n_A_batches": n_a,
        "n_B_batches": n_b,
        "method": "paired batch differences",
        "result": result,
        "direction": direction,
        "better_design_id": better_design_id,
        "better_design": better_design,
        "interpretation": interpretation,
    }


def run_pairwise_comparisons(designs: dict) -> pd.DataFrame:
    rows = []
    design_list = list(designs.values())

    for design_a, design_b in itertools.combinations(design_list, 2):
        rows.append(paired_pairwise_interval(design_a, design_b))

    results = pd.DataFrame(rows)
    if len(results) != C_COMPARISONS:
        raise ValueError(f"Expected {C_COMPARISONS} comparisons, got {len(results)}.")

    return results.sort_values("delta_A_minus_B").reset_index(drop=True)


# ── SUMMARIES ─────────────────────────────────────────────────────────────────
def build_design_summary(designs: dict, pairwise_results: pd.DataFrame) -> pd.DataFrame:
    summary_rows = []

    for design in designs.values():
        label = design["label"]
        design_id = design["design_id"]

        wins = (pairwise_results["better_design_id"] == design_id).sum()

        losses = (
            ((pairwise_results["design_A_id"] == design_id) & (pairwise_results["result"] == "B significantly better"))
            | ((pairwise_results["design_B_id"] == design_id) & (pairwise_results["result"] == "A significantly better"))
        ).sum()

        ns = (
            ((pairwise_results["design_A_id"] == design_id) | (pairwise_results["design_B_id"] == design_id))
            & (pairwise_results["result"] == "not significantly different")
        ).sum()

        summary_rows.append({
            "design_id": design_id,
            "label": label,
            "short_label": design["short_label"],
            "urgent_slots": design["urgent_slots"],
            "strategy": design["strategy"],
            "rule": design["rule"],
            "rule_name": design["rule_name"],
            "mean_OV": design["mean_OV"],
            "lower95": design["lower95"],
            "upper95": design["upper95"],
            "n_batches": design["n_batches"],
            "significant_wins": int(wins),
            "significant_losses": int(losses),
            "not_significant_pairs": int(ns),
        })

    return (
        pd.DataFrame(summary_rows)
        .sort_values(["mean_OV", "significant_losses", "significant_wins"], ascending=[True, True, False])
        .reset_index(drop=True)
    )


def build_significance_matrix(designs: dict, pairwise_results: pd.DataFrame) -> pd.DataFrame:
    labels = [d["short_label"] for d in designs.values()]
    id_to_short = {d["design_id"]: d["short_label"] for d in designs.values()}

    matrix = pd.DataFrame("", index=labels, columns=labels)

    for d in designs.values():
        matrix.loc[d["short_label"], d["short_label"]] = "—"

    for _, row in pairwise_results.iterrows():
        a = id_to_short[row["design_A_id"]]
        b = id_to_short[row["design_B_id"]]

        if row["result"] == "A significantly better":
            matrix.loc[a, b] = "row better"
            matrix.loc[b, a] = "column better"
        elif row["result"] == "B significantly better":
            matrix.loc[a, b] = "column better"
            matrix.loc[b, a] = "row better"
        else:
            matrix.loc[a, b] = "n.s."
            matrix.loc[b, a] = "n.s."

    return matrix


# ── REPORTING ─────────────────────────────────────────────────────────────────
def print_report(pairwise_results: pd.DataFrame, design_summary: pd.DataFrame) -> None:
    print("=" * 88)
    print("ALL PAIRWISE COMPARISON — PAIRED BATCH DIFFERENCES")
    print("=" * 88)
    print(f"Raw output folder: {OUTPUT_DIR}")
    print(f"Results folder:    {RESULTS_DIR}")
    print(f"k = {K_DESIGNS} candidate designs")
    print(f"c = k(k-1)/2 = {K_DESIGNS}({K_DESIGNS}-1)/2 = {C_COMPARISONS} pairwise comparisons")
    print(
        f"Bonferroni: alpha_per_CI = {ALPHA}/{C_COMPARISONS} = {ALPHA / C_COMPARISONS:.6f}; "
        f"individual CI level = {(1 - ALPHA / C_COMPARISONS) * 100:.3f}%"
    )
    print(f"Overall confidence level >= {(1 - ALPHA) * 100:.1f}%")
    print("Method: paired batch differences; df = n_batches - 1")
    print("=" * 88)

    print("\nDesign mean ranking, lower OV is better:")
    print(
        design_summary[
            ["design_id", "label", "mean_OV", "lower95", "upper95", "significant_wins", "significant_losses"]
        ].to_string(index=False, float_format=lambda x: f"{x:.6f}")
    )

    print("\nPairwise results:")
    print(
        pairwise_results[
            ["design_A_id", "design_B_id", "delta_A_minus_B", "ci_lower", "ci_upper", "result", "better_design"]
        ].to_string(index=False, float_format=lambda x: f"{x:.6f}")
    )


# ── PLOTS ─────────────────────────────────────────────────────────────────────
def plot_pairwise_forest(pairwise_results: pd.DataFrame) -> Path:
    plot_df = pairwise_results.sort_values("delta_A_minus_B", ascending=True).reset_index(drop=True)

    y_pos = np.arange(len(plot_df))
    fig_height = max(8, 0.38 * len(plot_df))
    fig, ax = plt.subplots(figsize=(12, fig_height))

    ax.axvline(0, color="black", linewidth=1.1, linestyle="--", zorder=1)

    colors = [COLORS[d] for d in plot_df["direction"]]
    xerr = [
        plot_df["delta_A_minus_B"] - plot_df["ci_lower"],
        plot_df["ci_upper"] - plot_df["delta_A_minus_B"],
    ]

    pair_labels = [
        f"{a} − {b}" for a, b in zip(plot_df["design_A_id"], plot_df["design_B_id"])
    ]

    ax.barh(
        y_pos,
        plot_df["delta_A_minus_B"],
        xerr=xerr,
        color=colors,
        alpha=0.85,
        height=0.65,
        error_kw={"elinewidth": 1.1, "capsize": 3, "ecolor": "#444"},
        zorder=2,
    )

    for i, row in plot_df.iterrows():
        offset = 0.0004 if row["delta_A_minus_B"] >= 0 else -0.0004
        ha = "left" if row["delta_A_minus_B"] >= 0 else "right"
        ax.text(
            row["delta_A_minus_B"] + offset,
            i,
            f"{row['delta_A_minus_B']:+.5f}",
            va="center",
            ha=ha,
            fontsize=8,
            color="#333",
        )

    ax.set_yticks(y_pos)
    ax.set_yticklabels(pair_labels, fontsize=8)
    ax.set_xlabel("Delta OV (design A − design B)")
    ax.set_title(
        "All pairwise comparison between the 7 retained alternatives\nPaired batch differences; df = n_batches - 1\n"
        f"k={K_DESIGNS}, c={C_COMPARISONS}, per-CI={(1 - ALPHA / C_COMPARISONS) * 100:.3f}%, "
        f"overall ≥ {(1 - ALPHA) * 100:.0f}%",
        fontsize=11,
        pad=12,
    )

    legend_handles = [
        Patch(color=COLORS["first_better"], alpha=0.85, label="Design A significantly better"),
        Patch(color=COLORS["second_better"], alpha=0.85, label="Design B significantly better"),
        Patch(color=COLORS["not_significant"], alpha=0.85, label="Not significantly different"),
    ]
    ax.legend(handles=legend_handles, loc="lower right", frameon=True, framealpha=0.9)

    ax.grid(axis="x", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()
    out_path = RESULTS_DIR / "all_pairwise_forest_plot.png"
    plt.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close()
    return out_path


def plot_mean_ranking(design_summary: pd.DataFrame) -> Path:
    plot_df = design_summary.sort_values("mean_OV", ascending=True).reset_index(drop=True)
    y_pos = np.arange(len(plot_df))

    fig, ax = plt.subplots(figsize=(10, 5.5))

    xerr = [
        plot_df["mean_OV"] - plot_df["lower95"],
        plot_df["upper95"] - plot_df["mean_OV"],
    ]

    ax.barh(
        y_pos,
        plot_df["mean_OV"],
        xerr=xerr,
        color="#B4B2A9",
        alpha=0.85,
        height=0.65,
        error_kw={"elinewidth": 1.1, "capsize": 3, "ecolor": "#444"},
    )

    for i, row in plot_df.iterrows():
        ax.text(
            row["upper95"] + 0.0005,
            i,
            f"{row['mean_OV']:.5f}",
            va="center",
            ha="left",
            fontsize=8,
            color="#333",
        )

    ax.set_yticks(y_pos)
    ax.set_yticklabels(plot_df["label"], fontsize=9)
    ax.invert_yaxis()
    ax.set_xlabel("Mean OV with ordinary 95% CI")
    ax.set_title("Mean OV ranking of retained alternatives", fontsize=11, pad=12)

    ax.grid(axis="x", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()
    out_path = RESULTS_DIR / "all_pairwise_mean_ranking.png"
    plt.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close()
    return out_path


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    clean_previous_outputs()

    designs = load_designs()
    pairwise_results = run_pairwise_comparisons(designs)
    design_summary = build_design_summary(designs, pairwise_results)
    significance_matrix = build_significance_matrix(designs, pairwise_results)

    print_report(pairwise_results, design_summary)

    pairwise_table_path = RESULTS_DIR / "all_pairwise_comparison_table.csv"
    design_summary_path = RESULTS_DIR / "all_pairwise_design_summary.csv"
    matrix_path = RESULTS_DIR / "all_pairwise_significance_matrix.csv"

    pairwise_results.to_csv(pairwise_table_path, index=False, float_format="%.8f")
    design_summary.to_csv(design_summary_path, index=False, float_format="%.8f")
    significance_matrix.to_csv(matrix_path)

    forest_path = plot_pairwise_forest(pairwise_results)
    ranking_path = plot_mean_ranking(design_summary)

    print(f"\nTable saved         -> {pairwise_table_path}")
    print(f"Design summary saved -> {design_summary_path}")
    print(f"Matrix saved        -> {matrix_path}")
    print(f"Forest plot saved   -> {forest_path}")
    print(f"Ranking plot saved  -> {ranking_path}")


if __name__ == "__main__":
    main()
